import type { TalkCard } from "./types";

export const CARDS: TalkCard[] = [
  {
    cat: "System design",
    color: "emerald",
    q: "Add caching to reward lookups without touching the business logic. How?",
    a: "Write a caching decorator adapter: a cachedRewardRepositoryCreator that wraps any RewardRepository, checks the cache first, delegates on miss. Same port on both sides. Swap it in at the composition root. Zero changes to the use case, and you can unit test the caching behavior in isolation.",
  },
  {
    cat: "System design",
    color: "emerald",
    q: "The redemption API is flaky. Where do retries, timeouts and circuit breaking live?",
    a: "In the adapter, or in a resilience decorator wrapping the port. The use case should not know the network exists. Bonus point: mention that the port's contract (throws vs returns a result type) is the one design decision the domain does own.",
  },
  {
    cat: "System design",
    color: "emerald",
    q: "Two use cases need to fetch a user. Do they share a port?",
    a: "Prefer ports scoped to what each use case needs (interface segregation). Sharing is fine when the need is genuinely identical, but a fat shared port slowly turns into a god interface that every adapter must fully implement.",
  },
  {
    cat: "System design",
    color: "emerald",
    q: "How would you structure the folders to make the boundary visible?",
    a: "domain (entities, ports, use cases) with zero external imports, adapters (one folder per technology), and a thin app or wiring layer as composition root. The import rule is the architecture: domain imports nothing from outside itself, and a lint rule can enforce it.",
  },
  {
    cat: "Product mindset",
    color: "violet",
    q: "Why does this architecture matter for a product built on third-party integrations?",
    a: "Such a product lives on third-party integrations: merchant APIs, banking data, reward providers. Those change and break outside your control. Ports isolate each partner behind a stable contract, so swapping a provider or adding a fallback is an adapter, not a rewrite. That is business agility, not just clean code.",
  },
  {
    cat: "Product mindset",
    color: "violet",
    q: "A PM asks for a quick hack that violates the boundary. What do you say?",
    a: "Connect cost to product: the hack ships today but makes the next ten features slower and riskier. Offer the middle path: ship behind the port with a rough adapter, refine the adapter later. The boundary is what makes 'later' cheap.",
  },
  {
    cat: "AI collaboration",
    color: "cyan",
    q: "How do you use the built-in AI assistant well during this interview?",
    a: "Narrate intent out loud before prompting, use the AI for boilerplate and recall (adapter scaffolding, test setup) while owning design decisions yourself, and review its output critically: say what you are checking and why. They evaluate how you think alongside it, so verbalize the division of labor.",
  },
  {
    cat: "AI collaboration",
    color: "cyan",
    q: "The AI generates code that puts a business rule in an adapter. What do you do?",
    a: "Catch it, name it, fix it. This is the moment they are hoping to see: you spot that the AI violated the boundary, explain why it matters, and move the rule into the use case. Trust but verify, out loud.",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "Sentence starters for reasoning out loud (say them until they are automatic)",
    a: "'Let me walk you through my reasoning.' 'The trade-off I see here is...' 'My first instinct is X, but let me check the boundary.' 'What this port expresses is a business need, namely...' 'I'd rather keep the domain vendor-neutral, so...' 'Before I write code, let me map the dependencies.'",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "Vocabulary you must be fluent with in English",
    a: "Boundary, coupling, cohesion, leaky abstraction, separation of concerns, single responsibility, dependency inversion, composition root, seam, stub, spy, test double, wiring, vendor lock-in, trade-off, 'to swap out', 'to hard-code', 'to ripple through the codebase'.",
  },
  {
    cat: "Codebase reading",
    color: "slate",
    q: "First 5 minutes with an unknown codebase in a live coding interview. What is your routine?",
    a: "1: find the composition root, it is the map of the system. 2: read the ports to learn the business vocabulary. 3: pick one use case and trace it end to end. 4: only then look inside adapters. Say this plan out loud, it demonstrates method before knowledge.",
  },
  {
    cat: "Codebase reading",
    color: "slate",
    q: "How do you quickly judge if a codebase really follows the pattern?",
    a: "Grep the domain folder for SDK imports, env vars, and fetch calls: it should be clean. Check whether tests use in-memory adapters or mocking libraries. Look for business rules hiding in adapters. Three checks, two minutes, strong signal.",
  },
  {
    cat: "Testing strategy",
    color: "emerald",
    q: "Why does the test pyramid shape fall out of the architecture instead of being a team policy?",
    a: "Because the boundary decides what is cheap. With ports around redeemReward, all the business logic runs against in-memory creators, so hundreds of millisecond-fast tests cost nothing to write or run. Each adapter then needs only a small integration suite proving translation against the real DynamoDB or the real redemption API, and one or two end-to-end paths confirm the wiring. The sentence to say is: 'the pyramid is not a policy we enforce, it is the shape a well-bounded codebase takes on its own.' If your pyramid is inverted, the boundary is missing, not the discipline.",
  },
  {
    cat: "Testing strategy",
    color: "emerald",
    q: "The interviewer asks: 'so you mock everything — do you ever test the real DynamoDB adapter?'",
    a: "Refuse the premise first: you do not mock, you substitute real in-memory implementations of the port, which are complete working code, not stubs with canned answers. Then answer yes: every adapter gets its own integration tests against the real dependency, so dynamoDbRewardRepositoryCreator has a small suite proving key shapes, marshalling, and null handling against DynamoDB Local or a test table. What the domain tests skip is not edge correctness, it is paying network latency on every business rule. Say: 'fast tests prove the rules, adapter tests prove the translation, and neither has to prove the other.'",
  },
  {
    cat: "Testing strategy",
    color: "emerald",
    q: "How do you guarantee the in-memory RewardRepository actually behaves like the DynamoDB one?",
    a: "With a contract test suite written once against the port and parameterized over creators. The same assertions run against inMemoryRewardRepositoryCreator on every commit and against dynamoDbRewardRepositoryCreator in integration CI: getById returns null for a missing reward, saved rewards round-trip, and so on. If the fake ever drifts from the real adapter, the contract suite fails before your domain tests start lying to you. A strong sentence in the discussion: 'the in-memory adapter is a first-class implementation, held to the same contract as production.'",
  },
  {
    cat: "Testing strategy",
    color: "emerald",
    q: "You are asked to TDD redeemReward live. Narrate your first ten minutes.",
    a: "Start outside-in: write a failing test for the whole use case in domain language — 'redeeming an expired reward returns an error, no cashback is granted'. Let that test force the ports into existence: it needs a RewardRepository, a RedemptionService, a Clock, so you sketch each interface and pass in in-memory fakes. Narrate the key move out loud: 'I am letting the test tell me which dependencies the use case needs, then injecting them instead of creating them.' Drive rule by rule from there; real adapters and composition-root wiring come last, once the behavior is pinned.",
  },
  {
    cat: "Testing strategy",
    color: "emerald",
    q: "You inherit a legacy cashback module with no tests and no boundaries. Where do you start?",
    a: "With characterization tests: pin the current behavior at the outermost seam you can reach, before changing a single line. These tests describe what the code does, not what it should do — if it rounds cashback wrong, the test asserts the wrong rounding, because your first job is a safety net, not a fix. Under that net, carve out the first port, usually around the ugliest dependency, and move logic behind it in small steps with the suite green throughout. The sentence to say is: 'first I make the change safe, then I make the safe change.'",
  },
  {
    cat: "Testing strategy",
    color: "emerald",
    q: "A test file opens with fifteen jest.mock calls. What is your diagnosis?",
    a: "Mocking effort is a design signal, not a testing problem. Each of those mocks marks a dependency the code constructed in place instead of receiving through a port, so the test has to perform surgery on module internals just to isolate one rule. The fix is not a cleverer mock, it is a port plus an in-memory creator injected as an argument, after which the mocks simply disappear. Say: 'when a test is this hard to write, the code is telling you where the boundary should have been.' That reframe, pain as diagnosis, is exactly what a senior answer sounds like.",
  },
  {
    cat: "System design",
    color: "emerald",
    q: "Explain the outbox pattern in four sentences.",
    a: "When redeemReward saves an Order and must also publish a RewardRedeemed event, the database and the broker are two systems, so the two writes cannot be atomic. So you write the event into an outbox table in the same transaction as the Order — one commit, both facts or neither. A separate relay process reads the outbox and publishes to the broker, retrying until acknowledged. You have traded dual-write inconsistency for at-least-once delivery, which is why every consumer downstream must be idempotent.",
  },
  {
    cat: "System design",
    color: "emerald",
    q: "A call to the redemption provider times out. Did the cashback go out? How do you design for this?",
    a: "A timeout is ambiguous: the request may have succeeded after you stopped waiting, so neither retrying blindly nor giving up is safe. The design answer is idempotency keys — every mutating call carries a redemption id generated before the call, and on retry the provider deduplicates instead of granting cashback twice. If the provider offers no idempotency, you record your intent in your own store before calling, then reconcile unknown outcomes with a status query or a periodic sweep. The sentence to say is: 'treat every timeout as a maybe, and design the system so retrying a maybe is always safe.'",
  },
  {
    cat: "System design",
    color: "emerald",
    q: "Where do authentication and authorization live in a hexagonal service?",
    a: "Authentication is an edge concern: the HTTP adapter validates the token and translates it into a domain identity — a plain userId — and nothing deeper ever sees a raw JWT or a session cookie. Authorization is a business rule: 'may this user redeem this reward' belongs in the use case, where it is testable with in-memory fakes and survives a swap from JWT to anything else. If a rule needs data, it comes through a port like OrderRepository, not from decoding claims mid-domain. A strong sentence in a system design discussion: 'authentication answers who at the edge; authorization answers may-they in the domain.'",
  },
  {
    cat: "Codebase reading",
    color: "slate",
    q: "You open the test folder before the source. What does it tell you about the architecture?",
    a: "Tests are the honest map, because tests cannot fake their own dependencies away. If the use-case suites run against in-memory creators with no mocking library in sight, the boundary is real and the fakes are maintained. If every test imports an aws-sdk mock or spins up containers to check one business rule, the domain is welded to infrastructure no matter what the folder names claim. The ratio of fast tests to slow ones mirrors the boundary exactly. In the interview, say: 'I read the tests first because tests can't lie about coupling.'",
  },
  {
    cat: "Codebase reading",
    color: "slate",
    q: "You have sixty seconds to tell whether the hexagon is real or decorative. What do you check?",
    a: "Three greps and one glance. Grep for process.env outside the composition root, for vendor imports like aws-sdk or axios inside domain and use-case files, and for clients being constructed inside use cases instead of arriving as parameters. Then open one port and check its vocabulary: RewardRepository returning a Reward is real; a port leaking DynamoDB Items or marshalled attributes is a vendor interface wearing a costume. Any single hit means the boundary is decorative, because a boundary with one hole is not a boundary.",
  },
  {
    cat: "Codebase reading",
    color: "slate",
    q: "Your review routine is to trace one HTTP request end to end. Walk me through it.",
    a: "Pick the hottest path, say POST /rewards/:id/redeem, and start at the handler: it should parse, validate shape, and call exactly one use case — anything more is a decision living at the edge. Follow into redeemReward and confirm it speaks only in port calls and business rules, with no client, no SDK, no env var. Then follow each port to its creator, and finish in the composition root where dynamoDbRewardRepositoryCreator and iFeelGoodsRedemptionServiceCreator get wired with their config. One full trace tells you more than an hour of folder browsing, because you see where each layer knows too much, not where the README says it stops.",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "You disagree with the interviewer's suggestion. Sentence templates?",
    a: "Frame it as a trade-off, never a correction. 'That would work — my concern is what it costs us the day the redemption provider changes.' 'I'd push back gently: if we filter rewards in the adapter, that rule disappears from the domain tests.' 'Help me see what I'm missing — my instinct is to keep that decision in the use case.' Disagreeing with a stated reason scores points; agreeing to be safe scores none.",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "Phrases for narrating TDD out loud while you type",
    a: "'I'll start with a failing test so we agree on the behavior before the implementation.' 'This is red for the right reason — redeemReward doesn't exist yet, it's not a typo.' 'Now the simplest thing that makes it green.' 'Green — so I can refactor safely.' Say each transition out loud; in a live coding interview, silence reads as confusion even when you are fine.",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "Trade-off sentence frames: shipping speed versus cost of change",
    a: "'This is faster today and more expensive every time the vendor changes.' 'I'd pay for the port here because the redemption provider is the part most likely to be swapped.' 'The question is not whether it's more code — it's where the next change lands.' A strong sentence in a system design discussion: 'I optimize for cost of change on the axes where change is likely, and for simplicity everywhere else.'",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "You are stuck, live, in front of the interviewer. What do you say?",
    a: "'Let me step back and restate the problem out loud.' 'I'll narrow it down: what is the smallest input that reproduces this?' 'I'm going to park this approach — it's costing more than it's returning — and try the in-memory repository instead.' Naming the stuck state buys you thinking time and reads as method, not panic. The one thing you must not do is go quiet.",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "Clarifying questions that sound senior, not hesitant",
    a: "'What does success look like at the end of the hour — working code, or design reasoning?' 'Should I treat the redemption API as reliable, or design for it failing?' 'Is cashback granted per order or per reward — and can one order redeem several rewards?' Senior questions surface constraints and edge cases; junior questions ask for permission. Ask two or three up front, state your assumptions, then commit.",
  },
  {
    cat: "English phrases",
    color: "amber",
    q: "Closing-summary phrases when you finish a code review",
    a: "'To summarize: the architecture is sound — ports, adapters, wiring in the composition root — with two decisions I'd move out of the adapters.' 'The one blocking issue is the business rule in the DynamoDB adapter; everything else is follow-up.' 'If I could change one thing, it would be making the Clock a port.' End with a ranked list: one blocker, a few improvements, one thing done well. A ranked close reads as judgment, not nitpicking.",
  },
  {
    cat: "Product mindset",
    color: "violet",
    q: "A PM asks why you spent two days on tests instead of shipping the next reward type. Your answer?",
    a: "Translate the investment into product terms: the suite is what makes the next ten reward types cheap, and what lets you swap redemption providers in a day instead of a month. Point at concrete money: a wrong grantCashback double-pays real users, and the test that catches it costs an hour. Then commit to a number, not a philosophy: 'this makes the next feature two days faster.' The sentence to say is: 'I'm not slowing this feature down — I'm buying the speed of the next five.'",
  },
  {
    cat: "Product mindset",
    color: "violet",
    q: "Legacy codebase, the boundary is violated everywhere. How do you refactor while still shipping features?",
    a: "Never a big-bang rewrite — strangle it. The rule: every feature you touch pays a small tax, so you extract a port on the seam you are already editing and leave the rest alone. Start where it hurts most, usually the vendor call — wrap the redemption API behind a RedemptionService port first, because that is where outages and provider changes bite. New code follows the pattern from day one; old code converts opportunistically. A strong sentence: 'I sequence the refactor along the roadmap, so the product never stops shipping while the architecture improves underneath it.'",
  },
  {
    cat: "Product mindset",
    color: "violet",
    q: "When would you NOT apply the full ports-and-adapters pattern?",
    a: "When the cost of change you are insuring against does not exist: a one-off migration script, a prototype you will genuinely delete, an internal tool that will only ever have one storage backend. The pattern is insurance, and you do not insure things you are about to throw away. Be honest that 'temporary' code often survives — so the real test is whether the domain logic is worth protecting, not how small the code is. Say: 'I apply it where the domain is stable and the edges are volatile; anywhere else it's ceremony.' Knowing when not to use the pattern is what proves you understand it.",
  },
  {
    cat: "AI collaboration",
    color: "cyan",
    q: "How do you prompt an AI pair to scaffold an adapter while keeping ownership of the design?",
    a: "You write the port first — RewardRepository, its methods, its error contract — because the port is the design decision and the adapter is mostly typing. Then the prompt is precise: 'implement dynamoDbRewardRepositoryCreator against this interface, dependencies as a parameter object, return domain types, no process.env.' Review the output at the boundary only: does it translate, or does it decide? The sentence to say is: 'I let the AI write the translation; I keep the contract.'",
  },
  {
    cat: "AI collaboration",
    color: "cyan",
    q: "The AI generated a test suite for redeemReward. How do you spot over-specification?",
    a: "Look for tests that pin the implementation instead of the behavior: asserting getById was called exactly once, asserting call order, or asserting on mock internals. Those tests fail on refactors that change nothing observable, which trains the team to ignore red. Keep the ones that assert outcomes — reward marked redeemed, cashback granted, rejection when the balance is insufficient — using the in-memory repository, and delete the rest. Say it out loud: 'a test that fails when I refactor without changing behavior has negative value.'",
  },
  {
    cat: "AI collaboration",
    color: "cyan",
    q: "Using AI to explore an unfamiliar interview codebase — where is the line?",
    a: "Use it for the mechanical mapping: 'list the ports', 'where is the composition root', 'which files read process.env'. Treat every answer as a hypothesis and verify it by opening the file — AI summaries of code are confidently wrong just often enough to burn you live. Never ask 'is this good architecture' and repeat the verdict; the interviewer is testing your judgment, not the model's. Narrate the division of labor: 'I'm using AI to find the boundary faster, then reading it myself.'",
  },
];
