import type { QuizQuestion, QuizSet } from "./types";

export const QUIZ: QuizQuestion[] = [
  {
    q: "What is a port?",
    options: [
      "A concrete class that talks to a database",
      "An interface defined by the inner logic that expresses a need",
      "A configuration file listing external services",
      "A network endpoint exposed by the app",
    ],
    answer: 1,
    why: "A port is written in the language of the business and states WHAT the logic needs, never HOW it is done. No SDKs, no HTTP, no database types.",
  },
  {
    q: "Who defines the port, and in whose vocabulary?",
    options: [
      "The infrastructure team, using the vendor's SDK types",
      "The framework, through its plugin system",
      "The inner business logic, in business language",
      "The API provider, through its OpenAPI spec",
    ],
    answer: 2,
    why: "Ports belong to the inside. That is the inversion: infrastructure conforms to the business, not the other way around.",
  },
  {
    q: "What is an adapter?",
    options: [
      "A concrete implementation of a port, living at the edge of the system",
      "A design pattern for converting one interface into another inside the domain",
      "A wrapper that hides business rules from the infrastructure",
      "A middleware that logs every request",
    ],
    answer: 0,
    why: "Adapters deal with the real world: databases, HTTP, auth, retries, timeouts, serialization. Ports define what is needed, adapters define how it is done.",
  },
  {
    q: "Can a single port have multiple adapters?",
    options: [
      "No, that would break the contract",
      "Yes, for example a DynamoDB adapter for prod and an in-memory adapter for tests",
      "Only if the adapters share a base class",
      "Only in dynamically typed languages",
    ],
    answer: 1,
    why: "That is the whole point. Prod adapter, in-memory adapter, tomorrow a Postgres adapter. The use case never changes.",
  },
  {
    q: "The use case defines ports but instantiates its own adapters inside the function. What is wrong?",
    options: [
      "Nothing, ports exist so the boundary is real",
      "Performance: adapters are created on every call",
      "The boundary is fake: infrastructure choices are still hard-coded in the logic",
      "It only breaks if the adapters are async",
    ],
    answer: 2,
    why: "Ports without injection are a fake boundary. The logic still decides HOW its dependencies are built, so testing still requires real infra or heavy mocking.",
  },
  {
    q: "What is the core principle of dependency injection?",
    options: [
      "Use a DI framework with decorators and a container",
      "Do not create dependencies where you use them; receive them from the outside",
      "Register every class as a singleton",
      "Inject configuration through environment variables",
    ],
    answer: 1,
    why: "No framework needed. A factory function receiving its dependencies as an argument is dependency injection.",
  },
  {
    q: "What is the composition root?",
    options: [
      "The root component of the React tree",
      "The only place in the system that chooses and wires adapters",
      "A base class every adapter must extend",
      "The main() function of the runtime",
    ],
    answer: 1,
    why: "Wiring happens in exactly one place. In-memory wiring for tests and local dev, production wiring for prod. The use case code never changes.",
  },
  {
    q: "Where should process.env.REWARDS_TABLE be read?",
    options: [
      "Inside the use case, so the logic knows its table",
      "Inside the port interface as a default value",
      "In the composition root, passed into the adapter's creator",
      "Anywhere, environment variables are global anyway",
    ],
    answer: 2,
    why: "Environment and config are infrastructure details. They enter through the wiring, never through the business logic.",
  },
  {
    q: "Why are in-memory adapters valuable?",
    options: [
      "They are faster in production than a real database",
      "Fast tests, local dev without AWS or Docker, and fully predictable state",
      "They avoid writing interfaces",
      "They replace the need for a composition root",
    ],
    answer: 1,
    why: "No network, no setup, and you control the exact state, for example pre-populating a Map with test data.",
  },
  {
    q: "Which of these does NOT belong in a port interface?",
    options: [
      "A method name expressing a business need, like getById",
      "A domain type, like Reward",
      "A DynamoDB.DocumentClient parameter",
      "A Promise return type",
    ],
    answer: 2,
    why: "SDK types leaking into a port tie the business to a vendor. That is a leaky abstraction: swap the database and the port breaks too.",
  },
  {
    q: "You migrate storage from DynamoDB to Postgres. What changes?",
    options: [
      "The use case, the port, and the adapter",
      "Only the adapter and the wiring in the composition root",
      "Only the port interface",
      "Everything, migrations always ripple",
    ],
    answer: 1,
    why: "Write a postgresRewardRepositoryCreator, swap it in the composition root, done. The port and use case are untouched. This is the answer they want to hear.",
  },
  {
    q: "How do you unit test a use case built with DI?",
    options: [
      "Spin up DynamoDB Local in Docker",
      "Monkey-patch the AWS SDK with a mocking library",
      "Inject in-memory adapters with pre-populated state and assert on behavior",
      "Mock global fetch and assert on the URL called",
    ],
    answer: 2,
    why: "Inject an in-memory repository seeded with the reward you need, a no-op or recording redemption service, then assert. Instant, deterministic, no mocking framework.",
  },
];

export const QUIZ_SETS: QuizSet[] = [
  {
    id: "s1",
    title: "Foundations: Ports and Adapters",
    questions: QUIZ,
  },
  {
    id: "s2",
    title: "Injection and the Composition Root",
    questions: [
      {
        q: "A candidate from a Java background writes classes with constructor injection instead of creator functions. Is this a different pattern?",
        options: [
          "No: both receive dependencies from the outside; the constructor parameters and the creator's parameter object are the same idea",
          "Yes: constructor injection only works with a DI framework resolving the classes",
          "Yes: closures leak memory over time, so classes are the safer pattern",
          "No, but only if the class also reads its own config from process.env",
        ],
        answer: 0,
        why: "A class storing constructor arguments in fields and a creator closing over a parameter object are mechanically different but principally identical: dependencies flow in from outside, and the caller decides what they are. The sentence to say is: 'the pattern is injection, the syntax is taste.'",
      },
      {
        q: "You are reviewing this use case:\n\nconst redeemReward = redeemRewardCreator({ locator });\n// inside:\nconst repo = locator.get('rewardRepository');\n\nWhat do you flag?",
        options: [
          "Nothing: the locator is itself injected, so this is dependency injection",
          "The string key should be a shared constant to prevent typos",
          "Service locator: the real dependencies are hidden inside the locator, so the signature no longer tells you what the use case needs",
          "The locator should be a module-level singleton instead of a parameter",
        ],
        answer: 2,
        why: "Injecting a locator injects everything and declares nothing. You cannot read the deps from the signature, tests must assemble a full locator instead of two fakes, and a renamed key fails at runtime instead of compile time. Injection means naming each dependency explicitly.",
      },
      {
        q: "A creator declares clock as a dependency but also has this at the top of its file:\n\nimport { dynamoClient } from '../infra/dynamoClient';\n\nWhat is the problem?",
        options: [
          "Module imports resolve more slowly than parameters",
          "Inconsistency: clock should also be a module import",
          "Nothing, as long as dynamoClient is only used for reads",
          "dynamoClient is a hidden dependency: invisible in the signature, unswappable without module mocking, and it drags AWS into every test",
        ],
        answer: 3,
        why: "Importing a live client makes the dependency ambient: the signature lies about what the code needs, and the only test seam left is jest.mock. Every dependency that varies between prod and test must arrive through the parameter object, where it can be seen and replaced.",
      },
      {
        q: "redeemRewardCreator receives { rewardRepository, clock } and returns an async function. Between the creator call at startup and a request an hour later, where does rewardRepository live?",
        options: [
          "In a global registry that the runtime maintains for injected values",
          "In the closure of the returned function: the creator's parameters stay reachable for as long as the function does",
          "Nowhere: it must be passed again on every call",
          "In a WeakMap keyed by the function, which the GC may clear under memory pressure",
        ],
        answer: 1,
        why: "Closures are the mechanism that makes factory-function DI work: the returned function captures its creator's scope, so dependencies persist without classes, fields, or a container. If you can explain this in one sentence at the whiteboard, the whole style stops looking like magic.",
      },
      {
        q: "Inside dynamoDbRewardRepositoryCreator a teammate adds a fallback 'so callers don't have to pass it':\n\ntableName: tableName ?? process.env.REWARDS_TABLE\n\nWhat do you say in review?",
        options: [
          "Remove it: the adapter now has a hidden dependency on the environment and two sources of truth for one value; env is read once in the wiring and passed in explicitly",
          "Keep it: defensive defaults make adapters more robust in production",
          "Move the fallback up into the use case instead of the adapter",
          "Keep it, but validate the env var with a schema inside the adapter",
        ],
        answer: 0,
        why: "With the fallback, the same creator call behaves differently per machine, and a test that forgets tableName silently hits whatever the shell exports. Config crosses the boundary exactly once, at the composition root, so every adapter's behavior is fully determined by its arguments.",
      },
      {
        q: "You open an interview codebase cold with fifteen minutes to understand it. Where do you go first, and why?",
        options: [
          "The README, because architecture documentation is authoritative",
          "The test folder, since tests are executable documentation",
          "The composition root: it lists every use case, which adapter implements each port, and where every piece of config enters, all in one file; it is the map of the system",
          "The domain entities, since everything else depends on them",
        ],
        answer: 2,
        why: "A single wiring place buys a property nothing else gives you: the entire object graph is readable top to bottom in one file. Saying 'I always start with the composition root, it's the map' is a strong opening sentence in a code review interview.",
      },
      {
        q: "You find dynamoDbRewardRepositoryCreator called in three different HTTP handler files, each reading process.env itself. What is the real cost?",
        options: [
          "Slightly slower cold starts from constructing duplicate clients",
          "Assembly is scattered: there is no single map of the system, config parsing is triplicated, and swapping to Postgres means hunting down every call site",
          "None, as long as all three handlers pass the same table name",
          "The handlers can no longer be deployed independently of each other",
        ],
        answer: 1,
        why: "Duplicate clients are a minor perf issue; the architectural cost is losing the single wiring place. Scattered assembly means the adapter swap that should be a one-line change in the root becomes a repo-wide search, and each site can drift to different config.",
      },
      {
        q: "Your end-to-end tests exercise the full HTTP app but must not touch AWS or the redemption vendor. What is the clean setup?",
        options: [
          "Mock the AWS SDK at module level with jest.mock in the test bootstrap",
          "Point the production wiring at a dedicated staging AWS account",
          "Skip end-to-end tests; unit tests with fakes already cover the logic",
          "A test composition root: the same use cases and handlers, with inMemoryRewardRepositoryCreator and a fake redemption service swapped in at the wiring level",
        ],
        answer: 3,
        why: "Because all assembly happens in one place, a second wiring is cheap: swap the edge adapters, keep everything between them real. That is the payoff of test wiring versus prod wiring, and it needs zero module mocking.",
      },
      {
        q: "When is a DI container actually justified?",
        options: [
          "When the graph is genuinely large and needs lifetime management, such as request-scoped dependencies, and even then it lives only inside the composition root",
          "As soon as any creator has more than three dependencies",
          "Always: manual wiring does not scale beyond toy projects",
          "Never: containers are the wrong choice in every ecosystem",
        ],
        answer: 0,
        why: "Manual wiring for a typical service is a few dozen explicit, greppable lines; a container trades that clarity for reflection and runtime resolution errors. A strong sentence in a system design discussion: 'I wire by hand until the wiring file, not the app, becomes the problem.'",
      },
      {
        q: "Consider the two calls:\n\nconst redeemReward = redeemRewardCreator({\n  rewardRepository,\n  redemptionService,\n  clock,\n});\n\nawait redeemReward({ userId, rewardId });\n\nWhy do dependencies and request data arrive separately?",
        options: [
          "TypeScript cannot type a single call mixing both kinds of argument",
          "It avoids allocating the dependency object per request, a pure performance choice",
          "It is partial application: dependencies are fixed once at startup in the wiring, and only per-request data crosses the boundary at call time",
          "It lets the creator memoize results across requests sharing a userId",
        ],
        answer: 2,
        why: "The two calls belong to two lifecycles: the creator runs once, at wiring time; the returned function runs per request. Callers of redeemReward never see or care about its dependencies, which is exactly the decoupling injection is for.",
      },
      {
        q: "To make tests easier, a teammate exposes setRewardRepository(repo) so tests can swap the repository held in a module-level variable. What is the flaw?",
        options: [
          "The setter must be async to be safe under concurrent requests",
          "It reintroduces ambient mutable state: tests become order-dependent, cannot run in parallel, and production code can be silently rewired from anywhere",
          "Nothing: this is a standard, accepted test seam",
          "The setter should live on the use case object rather than the module",
        ],
        answer: 1,
        why: "A mutable module variable is a global with a nicer name; one test forgetting to reset it poisons the next. With creator-based DI each test builds its own instance with its own fakes, so there is no shared state to swap or restore.",
      },
      {
        q: "The composition root imports the DynamoDB SDK, concrete adapters, and domain use cases all in one file. A teammate calls this a dependency-rule violation. Is it?",
        options: [
          "Yes: split it into one wiring file per layer to restore the boundaries",
          "Yes: the root should import only interfaces, never implementations",
          "Yes, but it is acceptable technical debt at small scale",
          "No: the root is the one module allowed to know everything; it sits at the outermost edge, depends on all layers, and nothing depends on it",
        ],
        answer: 3,
        why: "The dependency rule says arrows point inward, and the root is where the arrows get assembled, so it must see both ends of every one. It is the dirtiest file in the system and the most honest: everything concrete is named there so it can stay unnamed everywhere else.",
      },
    ],
  },
  {
    id: "s3",
    title: "Unit Testing and Test Doubles",
    questions: [
      {
        q: "The inMemoryRewardRepositoryCreator returns a Map-backed implementation of RewardRepository that really stores and retrieves rewards. A teammate calls it 'the mock repository'. What is the precise term?",
        options: [
          "A mock, since it replaces the real database",
          "A stub, since it returns predictable data",
          "A fake: a working implementation taking a shortcut",
          "A dummy, since it never ships to production",
        ],
        answer: 2,
        why: "A fake has real behavior — save then getById actually round-trips — it just takes a shortcut like memory instead of DynamoDB. Mocks verify expectations, stubs return canned answers. Using the vocabulary precisely is worth a sentence in the interview.",
      },
      {
        q: "You are testing a branch of grantCashback that never touches its OrderRepository dependency, so you pass {} as OrderRepository just to satisfy the signature. What kind of test double is that?",
        options: [
          "A dummy: it exists only to fill a parameter",
          "A stub: it stands in for the real repository",
          "A spy: it observes that nothing was called",
          "A fake: an empty but valid implementation",
        ],
        answer: 0,
        why: "A dummy is passed but never used. It has a diagnostic bonus: if the test crashes because the dummy was called, the code path touches more than you thought.",
      },
      {
        q: "You review this hand-rolled helper in an interview codebase:\n\nconst redemptionServiceSpy = () => {\n  const calls: string[] = [];\n  const service: RedemptionService = {\n    redeem: async (rewardId) => {\n      calls.push(rewardId);\n    },\n  };\n  return { service, calls };\n};\n\nWhat is it?",
        options: [
          "A stub, because redeem returns nothing useful",
          "A mock, because it fails on unexpected calls",
          "A fake, because it implements the whole port",
          "A spy: it records calls for the test to assert on later",
        ],
        answer: 3,
        why: "A spy records interactions and leaves the assertion in the test; a mock carries expectations and verifies itself. Ten lines, no framework — hand-rolled recording adapters are the house style when ports are small.",
      },
      {
        q: "A test file for redeemReward opens with jest.mock('../adapters/dynamoDbRewardRepository'). What should you conclude?",
        options: [
          "Nothing; module mocking is standard Jest practice",
          "The use case imports its adapter directly, so DI is broken somewhere",
          "The adapter is too slow to run in unit tests",
          "The team should switch to jest.spyOn for cleaner syntax",
        ],
        answer: 1,
        why: "If the repository were injected, the test would just pass a fake as an argument. Patching the module system means the dependency is hard-wired at import time — jest.mock is a workaround for missing DI, and a smell to name out loud in review.",
      },
      {
        q: "redeemReward checks expiry with 'if (reward.expiresAt < new Date())' inline, and the suite went red at midnight before a release. What is the fix?",
        options: [
          "Inject a Clock port and pass a fixed clock in tests",
          "Call jest.useFakeTimers() in every affected test file",
          "Regenerate fixture dates from Date.now() in beforeEach",
          "Allow a one-day tolerance when comparing dates",
        ],
        answer: 0,
        why: "new Date() is hidden I/O: time is an input, so make it one. A Clock port makes the rule deterministic forever; fake timers and rolling fixtures only patch the symptom and leave the coupling in place.",
      },
      {
        q: "A test asserts that redeemReward returns the redeemed reward, and also that repository.getById was called exactly once with the id. You refactor the use case to merge two lookups into one; behavior is unchanged but the test fails. What went wrong?",
        options: [
          "The refactor is wrong; call counts are part of the contract",
          "The lookup cache should have been injected as its own port",
          "The test over-specified implementation; assert outcomes, not call counts",
          "The test needed a mock with relaxed expectations",
        ],
        answer: 2,
        why: "A test that fails while behavior stays the same is a tax on every refactor. Assert on return values and on observable state in the fakes; call-count assertions belong only where the call itself is the behavior, like sending an email once.",
      },
      {
        q: "In a given-when-then test for redeemReward, where does 'seed the in-memory repository with an expired reward' belong?",
        options: [
          "Then: it sets up what you assert against",
          "Given: it arranges the world before the action",
          "When: it is part of exercising the system",
          "Nowhere: seeding belongs in a beforeEach hook",
        ],
        answer: 1,
        why: "Given is the state of the world, when is the single action — calling the use case — and then asserts the outcome. Written this way, the test reads as a specification sentence, which is exactly what you want an interviewer to see.",
      },
      {
        q: "Which test name will serve you best when it fails in CI six months from now?",
        options: [
          "'test redeemReward #3'",
          "'redeemReward works correctly'",
          "'should call getById and then redeem'",
          "'rejects redemption when the reward has expired'",
        ],
        answer: 3,
        why: "A name stating behavior tells you what broke before you open the file. 'should call getById and then redeem' names the implementation, so it rots with the next refactor even when the rule still holds.",
      },
      {
        q: "You find this in a test file:\n\nconst failingRedemptionService: RedemptionService = {\n  redeem: async () => {\n    throw new RedemptionUnavailableError();\n  },\n};\n\nWhat is it, and why write it?",
        options: [
          "A throwing stub: the cheapest way to unit test the error path",
          "A chaos-engineering probe that belongs in staging",
          "A mock verifying that redeem is never called",
          "A fake that should also implement the happy path",
        ],
        answer: 0,
        why: "Most suites test only success, and error paths are where interviews are lost. One canned-failure stub covers the sad branch with zero network. The sentence to say is: 'I make the double fail on purpose to test what the use case does about it.'",
      },
      {
        q: "Which of these is a waste of unit-testing effort?",
        options: [
          "The expiry rule in redeemReward, driven by a fixed Clock",
          "The failure branch when grantCashback finds no Order",
          "The in-memory fake's conformance to the RewardRepository port",
          "dynamoDbRewardRepositoryCreator against a mocked DynamoDB client",
        ],
        answer: 3,
        why: "Mocking the vendor SDK only proves your mock matches your assumptions about DynamoDB — the one thing that can actually break is the real boundary, which a unit test cannot reach. Unit-test decisions; verify adapters against the real thing elsewhere.",
      },
      {
        q: "A teammate seeds test state with '(repo as any).rewards.push(expiredReward)'. What do you tell them?",
        options: [
          "Fine: tests are allowed to reach anywhere for speed",
          "Seed through the port or a creator parameter like initialRewards",
          "Move the push into a shared beforeEach so it is centralized",
          "Use a snapshot of production data instead",
        ],
        answer: 1,
        why: "Casting to any couples the test to the fake's private internals, so renaming the array breaks every test. inMemoryRewardRepositoryCreator({ initialRewards }) or await repo.save(...) arranges state through the public surface and survives change.",
      },
      {
        q: "The unit suite covering every use case — 80 tests — runs in 40 milliseconds. What is the strong sentence to say about that in an interview?",
        options: [
          "'We should add assertions; that speed is suspicious'",
          "'Fast tests mean thin coverage; we compensate elsewhere'",
          "'Speed here is a design signal: the domain contains no I/O'",
          "'We tuned Jest workers until the suite got this quick'",
        ],
        answer: 2,
        why: "Microsecond tests are not a performance achievement, they are proof the hexagon holds: pure decisions plus in-memory fakes. The day a unit test needs a network call or a sleep, an adapter has leaked into the domain — speed is the early alarm.",
      },
    ],
  },
  {
    id: "s4",
    title: "Integration Tests and the Pyramid",
    questions: [
      {
        q: "An integration test for dynamoDbRewardRepositoryCreator exists to verify exactly one thing. Which?",
        options: [
          "That the adapter correctly translates: key shapes, marshalling, query syntax, all exercised against a real DynamoDB engine",
          "That redeemReward rejects expired rewards when reading from a real table",
          "That the RewardRepository port interface is well designed",
          "That the composition root wires the right adapter for production",
        ],
        answer: 0,
        why: "Business rules are already unit-tested through the port with the in-memory adapter, and wiring is a smoke test's job. The integration test earns its runtime cost by proving the one thing no other test can: that the translation code speaks real DynamoDB.",
      },
      {
        q: "The team accepts that each adapter integration test takes 2-3 seconds while unit tests run in milliseconds. Why is that trade acceptable?",
        options: [
          "Slow tests are more thorough, so slower is strictly better",
          "It is not acceptable; integration tests must be optimized down to milliseconds too",
          "The test runner parallelizes, so per-test latency never matters",
          "Because they are few: the boundary keeps adapters thin, so a handful of slow tests covers all translation while thousands of fast unit tests cover the rules",
        ],
        answer: 3,
        why: "The speed budget follows the count. Fifteen 3-second tests make a 45-second stage; the same latency across 2000 tests makes the suite unusable. The pyramid tolerates slowness only where the architecture keeps volume low.",
      },
      {
        q: "A teammate labels this an integration test for the DynamoDB adapter:\n\nconst dynamoClient = {\n  get: jest.fn(() => ({\n    promise: () => Promise.resolve({\n      Item: { rewardId: 'r1', points: 100 },\n    }),\n  })),\n};\nconst repo = dynamoDbRewardRepositoryCreator({\n  dynamoClient, tableName: 'rewards',\n});\n\nWhat does it actually verify?",
        options: [
          "The full integration, since the real creator function is exercised",
          "The port contract, since the return type is checked at compile time",
          "Almost nothing: it proves the adapter calls the mock the way the mock was written to be called; key names, marshalling and query syntax stay untested",
          "The composition root wiring, since the creator is invoked with deps",
        ],
        answer: 2,
        why: "An integration test exists to catch the mistakes a mock cannot see: a wrong key name, wrong marshalling, a wrong TableName. Mocking the SDK removes the only thing worth testing at this level. The sentence to say is: 'this is a unit test of nothing'.",
      },
      {
        q: "What is a port-contract test suite?",
        options: [
          "A TypeScript type-level test checking that adapters compile against the interface",
          "A single shared suite of behavioral tests written against the RewardRepository port, executed against both the in-memory adapter and the DynamoDB adapter",
          "The set of unit tests for the use cases that consume the port",
          "A runtime schema validation layer generated from the port interface",
        ],
        answer: 1,
        why: "The compiler checks shape, not behavior. The contract suite pins down semantics — getById returns null for a missing reward, save then getById round-trips — and every adapter, fake or real, must pass the exact same suite.",
      },
      {
        q: "The contract suite runs against inMemoryRewardRepositoryCreator on every commit. What failure mode does that run specifically prevent?",
        options: [
          "Fake drift: the in-memory adapter silently diverging from real adapter behavior, so unit tests keep passing against semantics production no longer has",
          "Flaky network calls leaking into unit tests",
          "The DynamoDB adapter regressing on marshalling",
          "Duplicated test code between the fake and real suites",
        ],
        answer: 0,
        why: "Every unit test that uses the fake inherits the fake's assumptions. If the real adapter returns null for a missing reward and the fake starts throwing, hundreds of green unit tests now describe a world that does not exist. The shared contract is the tether.",
      },
      {
        q: "Your integration tests for the DynamoDB adapter need a real query engine. A teammate proposes pointing them at the shared staging table in AWS. What is the better option?",
        options: [
          "Accept staging; it is the closest thing to production",
          "DynamoDB Local or a testcontainer spun up per CI run: a real query engine with isolated data, no shared state, no AWS credentials or bill in CI",
          "Mock the DocumentClient so no engine is needed at all",
          "Run them against production with a cleanup script afterwards",
        ],
        answer: 1,
        why: "Shared environments make tests flaky — parallel runs collide on the same table — and drag credentials into CI. DynamoDB Local exercises the same query semantics with none of that. Mocking abandons the entire point of the test.",
      },
      {
        q: "You audit an interview codebase: 280 end-to-end browser tests, 30 integration tests, 9 unit tests. What are you looking at, and what is the cost?",
        options: [
          "A healthy pyramid, since end-to-end coverage is maximal",
          "The testing trophy, a modern alternative to the pyramid",
          "The ice-cream cone: feedback takes tens of minutes, failures are flaky and hard to attribute, and the team decays into a re-run-until-green culture",
          "A pyramid that merely needs more unit tests appended to it",
        ],
        answer: 2,
        why: "The cone usually means the rules are trapped inside handlers and SDK calls, so the browser is the only place they can be tested. The fix is architectural — pull the rules behind ports — not simply writing more unit tests around untestable code.",
      },
      {
        q: "In a well-factored hexagonal service, what belongs in the end-to-end layer?",
        options: [
          "Every business-rule permutation, re-verified through real HTTP",
          "Nothing; unit plus integration coverage makes e2e redundant",
          "One test per adapter, duplicating the contract suite over HTTP",
          "A few smoke tests: one happy path per critical flow, proving the composition root wired real adapters into a working whole",
        ],
        answer: 3,
        why: "End-to-end is the only level that exercises the wiring itself — config, credentials, the composition root. That surface is small, so a handful of smoke tests covers it. The rule permutations were already settled in millisecond unit tests.",
      },
      {
        q: "A strong sentence in a system design discussion: 'The test pyramid is not a policy we enforce, it is...' How does it end?",
        options: [
          "'...a consequence of the boundary: rules behind ports get thousands of millisecond tests, thin adapters need few integration tests, and wiring needs a couple of smoke tests'",
          "'...a budget: we cap integration tests at ten percent of the suite'",
          "'...a legacy idea: the testing trophy replaced it once integration tests got fast'",
          "'...a tooling problem: with enough parallel CI runners, the ratios stop mattering'",
        ],
        answer: 0,
        why: "Teams that enforce ratios by decree end up fighting their own architecture. With the hexagon in place the ratios fall out on their own; with a tangle, no policy will produce a pyramid. The shape is a symptom, not a rule.",
      },
      {
        q: "You find this in the test folder:\n\nconst rewardRepositoryContract = (\n  makeRepo: () => Promise<RewardRepository>,\n) => {\n  it('returns null for an unknown id', async () => {\n    const repo = await makeRepo();\n    expect(await repo.getById('missing')).toBeNull();\n  });\n};\n\nHow should it be consumed?",
        options: [
          "Only against the DynamoDB adapter; the fake keeps its own separate tests",
          "Only against the in-memory adapter, to keep the whole suite fast",
          "Invoked twice: with the in-memory creator in the fast suite, and with the DynamoDB creator backed by DynamoDB Local, tagged as integration",
          "Inlined into each use case's unit tests so behavior is checked in context",
        ],
        answer: 2,
        why: "One behavioral spec, two executions. The fake run keeps every commit honest at millisecond cost; the real run proves the same semantics survive actual DynamoDB. Splitting into two diverging suites is exactly how fake drift starts.",
      },
      {
        q: "How do you organize the full suite in CI so the cost stays sane?",
        options: [
          "Run everything on every push; completeness beats latency",
          "Tag by level: unit tests on every push in seconds, container-backed integration tests on the PR pipeline, a small smoke pass after deploy",
          "Run integration tests nightly only, since adapters rarely change",
          "Delete the integration tests once the contract suite passes on the fake",
        ],
        answer: 1,
        why: "The pyramid is also a spend plan: millisecond tests are effectively free so they gate everything, container-backed tests run where the environment exists, smoke tests run where the wiring is real. Nightly-only means adapter breakage lands after merge, when it is expensive to trace.",
      },
      {
        q: "You review this test running against DynamoDB Local:\n\nit('rejects redemption of an expired reward', async () => {\n  await repo.save(expiredReward);\n  const result = await redeemReward({\n    rewardRepository: repo,\n  })({ rewardId: expiredReward.id });\n  expect(result.ok).toBe(false);\n});\n\nWhat is the review comment?",
        options: [
          "Approve: verifying the rule against real infrastructure is strictly stronger",
          "It should also inject a fake Clock so the expiry date is deterministic",
          "It should assert on a thrown error class instead of a result object",
          "Wrong level: expiry is a domain rule, provable in milliseconds with the in-memory adapter; against DynamoDB Local the test should only verify translation, such as save then getById round-tripping",
        ],
        answer: 3,
        why: "Every rule tested through a real database is a rule you can only afford to verify a few times, slowly. Integration tests must spend their seconds on what only they can prove — translation — and leave the rules to the base of the pyramid.",
      },
    ],
  },
  {
    id: "s5",
    title: "Decorators and Resilience",
    questions: [
      {
        q: "In hexagonal architecture, what exactly is a decorator?",
        options: [
          "An implementation of a port that wraps another implementation of the same port, adding behavior around delegation",
          "A TypeScript @decorator annotation that registers a class in the DI container",
          "An adapter that translates between two different ports",
          "A subclass of an adapter that overrides the methods it wants to change",
        ],
        answer: 0,
        why: "Same port in, same port out: the use case cannot tell a wrapped repository from a bare one. No annotations, no container, no inheritance, just a creator that receives an inner implementation and delegates to it.",
      },
      {
        q: "Why are decorators the textbook example of the open/closed principle?",
        options: [
          "Because they close the port to new methods while opening it to new adapters",
          "Because they let you modify the Dynamo adapter without recompiling the domain",
          "You add caching, retry or metrics to a port without touching the use case or the adapter; behavior is extended by wrapping, not by editing existing code",
          "Because decorators are fixed at compile time, keeping runtime behavior closed",
        ],
        answer: 2,
        why: "Open for extension, closed for modification: every cross-cutting concern becomes a new wrapper stacked in the composition root. The tested adapter and the tested use case never change.",
      },
      {
        q: "You review this creator:\n\nconst cachedRewardRepositoryCreator = ({\n  inner,\n  clock,\n  ttlMs,\n}: {\n  inner: RewardRepository;\n  clock: Clock;\n  ttlMs: number;\n}): RewardRepository => ...\n\nWhat makes it a decorator rather than an adapter?",
        options: [
          "It uses a Clock, and adapters never depend on time",
          "It has the Creator suffix, which is reserved for decorators",
          "It caches, and caching always counts as infrastructure",
          "It takes a RewardRepository as a dependency and returns a RewardRepository: same port in and out, delegation instead of translation",
        ],
        answer: 3,
        why: "An adapter translates a vendor (Dynamo, an HTTP API) into the port. A decorator never touches a vendor; it wraps the port itself, which is why it stacks on any adapter, including the in-memory one.",
      },
      {
        q: "What is the difference between\n\ntimeoutRedemptionServiceCreator({\n  inner: retryingRedemptionServiceCreator({\n    inner: service, attempts: 3,\n  }),\n  ms: 2000,\n})\n\nand\n\nretryingRedemptionServiceCreator({\n  inner: timeoutRedemptionServiceCreator({\n    inner: service, ms: 2000,\n  }),\n  attempts: 3,\n})?",
        options: [
          "None; decorator order never changes observable behavior",
          "Timeout outermost caps the whole call at 2s across all retries; retry outermost gives each attempt its own 2s, so worst case is about 6s",
          "Retry must always be outermost or the timeout error cannot be caught",
          "Timeout outermost cancels the inner retries mid-flight, so only one attempt ever runs",
        ],
        answer: 1,
        why: "Composition order is behavior, not style. The sentence to say in review: the outermost decorator sees the entire inner stack as a single call, so decide whether your latency budget covers one attempt or all of them.",
      },
      {
        q: "You review this wiring in the composition root:\n\nconst repo = cachedRewardRepositoryCreator({\n  inner: loggingRewardRepositoryCreator({\n    inner: dynamoRepo,\n    logger,\n  }),\n  clock,\n  ttlMs: 60000,\n});\n\nWhich calls does the logging decorator see?",
        options: [
          "Only cache misses; hits return before reaching the logger, so cached traffic is invisible in the logs",
          "Every call the use case makes, since logging is transparent",
          "Only cache hits, because misses bypass the stack and go straight to Dynamo",
          "None; a decorator can only log calls it initiates itself",
        ],
        answer: 0,
        why: "The cache is outermost, so a hit short-circuits the rest of the stack. If you want a log line per use-case call, wrap logging around the cache. Stacking order is an observable design decision made in the composition root.",
      },
      {
        q: "The iFeelGoods redemption API is flaky. A teammate adds a retry loop with a sleep inside the redeemReward use case. What do you say in review?",
        options: [
          "Fine, resilience is a business requirement so it belongs in the domain",
          "Move the loop into the HTTP handler so it retries closer to the caller",
          "The use case now knows the network exists; retries belong in the adapter or in a decorator wrapping RedemptionService, wired in the composition root",
          "Replace the loop with a resilience library configured via process.env inside the use case",
        ],
        answer: 2,
        why: "The use case should not know its dependency is remote, let alone flaky. Absorb the mess at the edge and the domain stays deterministic, its unit tests stay fast, and the retry policy becomes swappable without touching business logic.",
      },
      {
        q: "How do you unit test a TTL caching decorator for RewardRepository?",
        options: [
          "Spin up DynamoDB Local so the cache has something real to protect",
          "You cannot unit test it; TTL expiry needs real time to pass, so it requires an integration test",
          "Mock Date.now globally with the test framework and assert the internal cache map contents",
          "Wrap an in-memory inner that counts calls, inject a fake Clock, assert the second read skips the inner, advance the clock past the TTL, assert the inner is hit again",
        ],
        answer: 3,
        why: "The decorator knows only two ports: the inner repository and the Clock. Hand it fakes for both and TTL logic becomes fully deterministic — no sleeps, no global patching, no database. This is why even time is a port.",
      },
      {
        q: "A circuit-breaker decorator on RedemptionService has opened after five consecutive failures. What happens to the next redeemReward call?",
        options: [
          "It fails fast without calling the inner service, using the failure shape the port contract defines, until the cool-down lets a probe attempt through",
          "It queues the call and replays it automatically once the API recovers",
          "It falls back to the in-memory adapter so users still get redemptions",
          "It throws a raw vendor exception so the caller knows the breaker is open",
        ],
        answer: 0,
        why: "Open means stop hammering a dying dependency and answer immediately. The breaker must still speak the port's failure contract — the use case never learns a breaker exists. Silently queuing writes or serving fake redemptions from memory would invent business outcomes.",
      },
      {
        q: "The RedemptionService port returns Result<Redemption, RedemptionError> and is documented never to throw. What does that mean for a retry decorator?",
        options: [
          "Retries become impossible, since there is no exception to catch",
          "The decorator must inspect the returned error to decide what is retryable and must return the same Result shape: it implements the port, so it honors its contract",
          "The decorator should convert Results to exceptions internally and rethrow on the last failure",
          "The failure contract only binds adapters, so the decorator may throw once retries are exhausted",
        ],
        answer: 1,
        why: "A decorator is a port implementation like any other, and the failure contract is the one design decision the domain owns. Retry-on-returned-error is just an if on the error value, not a catch — the whole stack speaks Result from top to bottom.",
      },
      {
        q: "You need p99 latency for every RewardRepository.getById call, without touching the Dynamo adapter or the use case. Where does the timer go?",
        options: [
          "In the HTTP handler, timing the whole request",
          "In the Dynamo adapter, since it owns the network call",
          "In a metricsRewardRepositoryCreator wrapping the port, stacked in the composition root",
          "In the use case, since it initiates the call",
        ],
        answer: 2,
        why: "A metrics decorator times the inner call and reports, and the adapter stays a pure translator. A strong sentence in a system design discussion: the same wrapper will time the future Postgres adapter unchanged, because it depends on the port, not the vendor.",
      },
      {
        q: "Inside a logging decorator you find:\n\nasync getById(id: string): Promise<Reward | null> {\n  try {\n    return await inner.getById(id);\n  } catch (e) {\n    logger.error('getById failed', e);\n    return null;\n  }\n}\n\nWhat is the bug?",
        options: [
          "logger.error should be awaited, or log ordering becomes nondeterministic",
          "The decorator should log successes too, not only failures",
          "Nothing; converting failures to null keeps the use case simple",
          "It rewrites the port's failure contract: an outage now reads as 'reward not found'; a logging decorator observes and rethrows, it never changes outcomes",
        ],
        answer: 3,
        why: "The use case will treat null as a missing reward and take a business decision on top of an infrastructure failure. Decorators may add behavior around a call, never change what the call means.",
      },
      {
        q: "Which of these does NOT belong in a decorator around RewardRepository?",
        options: [
          "Caching reads with a TTL",
          "Filtering out expired rewards before returning them",
          "Recording call latency",
          "Retrying reads on transient Dynamo errors",
        ],
        answer: 1,
        why: "Expiry is a business rule; hidden in a wrapper it is invisible to domain tests and silently lost the day someone rewires the stack. Cross-cutting infrastructure concerns wrap the port; decisions go up into the use case.",
      },
    ],
  },
  {
    id: "s6",
    title: "Error Handling and Failure Contracts",
    questions: [
      {
        q: "In a hexagonal codebase, who owns the failure contract of the RewardRepository port — which failures exist and what they are called?",
        options: [
          "The adapter, since only it knows what can actually go wrong",
          "The HTTP layer, since it must map errors to status codes",
          "The domain: failures are declared on the port, in domain vocabulary",
          "The vendor SDK, since its exceptions are the ground truth",
        ],
        answer: 2,
        why: "The failure contract is part of the port, and the port belongs to the domain. Adapters translate whatever the vendor throws into those declared failures. The sentence to say is: 'how a port fails is as much a domain decision as what it returns.'",
      },
      {
        q: "What is the real trade-off between throwing domain errors and returning a Result/Either type from a use case?",
        options: [
          "Result puts failures in the type signature so the compiler forces callers to handle them; throwing keeps the happy path clean but makes failures invisible to the type system",
          "Throwing is faster at runtime, so hot paths must always throw",
          "Result types only work in functional languages, not in TypeScript",
          "Throwing is always wrong in a hexagon; every port must return Result",
        ],
        answer: 0,
        why: "Both styles are legitimate. What matters in the interview is naming the trade-off: explicit, compiler-checked failures versus an uncluttered happy path — and being consistent once the codebase has picked a side.",
      },
      {
        q: "A DynamoDB adapter for redeeming rewards contains:\n\n} catch (e) {\n  if (e.name === 'ConditionalCheckFailedException') {\n    throw new RewardAlreadyRedeemedError(id);\n  }\n  throw e;\n}\n\nWhat does a careful reviewer flag?",
        options: [
          "Nothing; known errors are translated and the rest propagate naturally",
          "The adapter should swallow unknown errors and return null",
          "The adapter should retry the write before throwing anything",
          "The bare rethrow leaks raw vendor exceptions across the port; unknown failures should become a RepositoryUnavailableError",
        ],
        answer: 3,
        why: "Translating the one error you expect is not enough. The fallback path rethrows AWS SDK exceptions straight into the domain, so callers end up coupled to DynamoDB the first time something unexpected fails. The adapter's catch block must translate everything, mapping the unknown to a generic infra error.",
      },
      {
        q: "Reviewing the redeemReward use case, you find it checking e.code === 'ThrottlingException' before deciding what to do. What went wrong upstream?",
        options: [
          "Nothing; the use case is the right place to handle throttling",
          "The adapter failed to translate: a vendor failure crossed the port, and the use case is now coupled to DynamoDB",
          "The port should have exposed the DynamoDB client so the check is at least explicit",
          "The composition root should be catching throttling instead",
        ],
        answer: 1,
        why: "The moment a vendor error name appears in a use case, the boundary has already been breached. The fix is not in the use case: it is in the adapter, which should have converted throttling into a domain-level RepositoryUnavailableError before it ever crossed the port.",
      },
      {
        q: "Why should the adapter throw a generic RepositoryUnavailableError rather than a DynamoDbTimeoutError?",
        options: [
          "It keeps the failure vocabulary vendor-neutral, so the Postgres adapter throws the exact same error and the use case never changes",
          "It lets the HTTP layer return 500 without a mapping table",
          "It avoids importing AWS SDK types, which are slow to compile",
          "It makes the error serializable across process boundaries",
        ],
        answer: 0,
        why: "The failure contract must survive an adapter swap, just like the happy path. If the use case caught DynamoDbTimeoutError, migrating to Postgres would silently break its error handling — the same ripple the hexagon exists to prevent.",
      },
      {
        q: "The redeemReward use case calls the redemption service and the reward repository. Which failures should it catch, and which should it let propagate?",
        options: [
          "Catch everything; a use case must never throw",
          "Propagate everything; catching is the HTTP handler's job",
          "Catch failures it has a business answer for, such as falling back to another fulfilment path; propagate failures it cannot act on, like RepositoryUnavailable",
          "Catch infra errors and convert them to HTTP 503 responses",
        ],
        answer: 2,
        why: "The rule is: catch what you can decide about, propagate what you cannot. If the business rule says a failed instant redemption falls back to a queued one, that catch is domain logic and belongs here. If the database is down, the use case has nothing to add — let it fly.",
      },
      {
        q: "Which layer turns RewardNotFoundError into a 404 and RewardAlreadyRedeemedError into a 409?",
        options: [
          "The use case, since it produced the errors",
          "The HTTP handler at the driving edge; status codes are a delivery concern",
          "The repository adapter, since it is closest to the data",
          "A global middleware that matches on error message strings",
        ],
        answer: 1,
        why: "The domain says what failed in its own vocabulary; the handler decides how that failure looks over HTTP. A CLI or a queue consumer would map the same domain errors completely differently. And mapping by message string instead of error type is a fragile trap, not a shortcut.",
      },
      {
        q: "You review a use case:\n\n} catch (e) {\n  return { status: 404, body: 'Reward not found' };\n}\n\nWhat is the flag?",
        options: [
          "The catch block should also log the error",
          "404 is the wrong code; a redeemed reward should be 410",
          "try/catch is forbidden inside use cases",
          "HTTP status codes leaked into the domain; the use case should raise a domain error and let the handler map it",
        ],
        answer: 3,
        why: "A use case returning { status: 404 } has quietly become an HTTP controller. It can no longer be reused from a queue consumer or a cron job, and its tests now assert transport details. Throw RewardNotFoundError here; map it to 404 at the edge.",
      },
      {
        q: "A call to grantCashback times out against the payment provider. What does the timeout actually tell you?",
        options: [
          "Nothing definite: the grant may or may not have happened, so a blind retry risks paying twice unless the request carries an idempotency key",
          "The operation failed, so it can be retried immediately",
          "The operation succeeded but the response was lost on the way back",
          "The circuit breaker should have prevented the call from being made",
        ],
        answer: 0,
        why: "A timeout is the one failure that proves nothing: the request may have died in flight or completed after you gave up. A strong sentence in a system design discussion: 'timeouts are ambiguous, so any non-idempotent write behind one needs an idempotency key before we talk about retries.'",
      },
      {
        q: "Which of these calls is safe to retry without any idempotency mechanism?",
        options: [
          "redemptionService.redeem(rewardId)",
          "cashbackService.grant(orderId, amount)",
          "rewardRepository.getById(rewardId)",
          "orderRepository.save(order) when save appends an event",
        ],
        answer: 2,
        why: "Reads are naturally idempotent: running getById twice changes nothing. The other three are writes with side effects — a double redeem, a double payment, a duplicated event. Retry policy is not one setting; it depends on the semantics of each operation.",
      },
      {
        q: "You add an idempotency key to the cashback grant so timeouts become safely retryable. Where should the key be generated?",
        options: [
          "Inside the adapter, fresh on every attempt",
          "By the payment provider, returned in its response",
          "From process.env in the composition root at boot",
          "Once, before the first attempt — for example derived from the order id — and kept stable across every retry so the provider can deduplicate",
        ],
        answer: 3,
        why: "The key only works if all retries of the same logical grant share it; a fresh key per attempt is just a decorated way to pay twice. Deriving it from a natural identifier like the order id makes the same business operation collapse to one payment no matter how many times the wire fails.",
      },
      {
        q: "A teammate documents a port:\n\ninterface RedemptionService {\n  /** @throws IFeelGoodsApiError on failure */\n  redeem(rewardId: string): Promise<void>;\n}\n\nWhat is wrong?",
        options: [
          "JSDoc cannot express throws clauses in TypeScript",
          "The vendor's error type is now part of the domain contract; the port must declare domain failures like RedemptionFailedError instead",
          "redeem should return a boolean instead of throwing",
          "Ports should not document failure behavior at all",
        ],
        answer: 1,
        why: "The comment quietly promises that every implementation — including the in-memory one used in tests — fails like the iFeelGoods SDK. That is the dependency arrow pointing the wrong way. Documenting failures on a port is exactly right; naming them after a vendor is exactly wrong.",
      },
    ],
  },
  {
    id: "s7",
    title: "The Delivery Edge",
    questions: [
      {
        q: "What distinguishes a driving port from a driven port?",
        options: [
          "Driving ports are asynchronous; driven ports are synchronous",
          "Driving ports are defined by adapters; driven ports by the domain",
          "Driving ports are how the world calls the application; driven ports are how the application calls the world",
          "Driving ports handle HTTP; driven ports handle databases",
        ],
        answer: 2,
        why: "Direction of the call is the whole distinction. An HTTP handler drives redeemReward from the outside; RewardRepository is driven because the use case calls out through it. Both sides can be sync or async, and neither is tied to a specific technology.",
      },
      {
        q: "Which of these is a driving adapter?",
        options: [
          "dynamoDbRewardRepositoryCreator",
          "An SQS consumer that parses a message and calls redeemReward",
          "iFeelGoodsRedemptionServiceCreator",
          "The in-memory RewardRepository used in tests",
        ],
        answer: 1,
        why: "HTTP handlers, CLI commands and queue consumers all sit on the driving side: they translate an incoming trigger into a use case call. The other three implement driven ports the application calls outward through.",
      },
      {
        q: "Which responsibility does NOT belong in an HTTP handler?",
        options: [
          "Parsing the request body into a typed object",
          "Rejecting a payload where rewardId is missing",
          "Checking whether the reward is still redeemable",
          "Mapping a domain error to a status code",
        ],
        answer: 2,
        why: "Redeemability is a business rule, so it lives in the use case where domain tests can see it. The handler's job is mechanical: parse, validate the shape, call the use case, translate the outcome. If the handler decides anything about rewards, it has stopped being thin.",
      },
      {
        q: "Where is the line between format validation and business rules at the delivery edge?",
        options: [
          "The handler rejects malformed input (wrong types, missing fields); the use case rejects well-formed requests that violate domain rules",
          "All validation lives in the use case so the handler stays thin",
          "All validation lives in the handler so the use case can fully trust its input",
          "Validation belongs in shared middleware that both layers call",
        ],
        answer: 0,
        why: "A rewardId sent as a number is a delivery problem; a reward that is expired is a domain problem. The sentence to say is: the handler validates that the request is well-formed, the use case validates that it is allowed.",
      },
      {
        q: "You are reviewing this use case:\n\nconst redeemRewardCreator =\n  ({ rewardRepository }: Deps) =>\n  async (req: express.Request): Promise<Reward> => {\n    const rewardId = req.params.rewardId;\n    ...\n  };\n\nWhat do you flag?",
        options: [
          "Nothing; the use case needs the request to read rewardId",
          "express.Request couples the use case to the framework; it should take a plain params object like { rewardId, userId }",
          "The use case should also receive the Response to set the status code",
          "req.params should be destructured in the function signature",
        ],
        answer: 1,
        why: "The moment express.Request appears in a use case signature, the domain imports the framework and every non-HTTP caller — tests, CLI, queue consumer — must fabricate a fake request. The handler extracts primitives and passes a plain object; the use case never learns HTTP exists.",
      },
      {
        q: "A teammate's use case returns { status: 404 } when a reward is not found. What is wrong?",
        options: [
          "Nothing; status codes are a universal vocabulary every developer knows",
          "It should return 410 Gone, since the reward may have existed before",
          "The status codes should come from a shared constants module",
          "404 is delivery vocabulary; the use case should signal the failure in domain terms, like a RewardNotFoundError, and the handler maps that to 404",
        ],
        answer: 3,
        why: "Status codes only mean something over HTTP. When the same use case is triggered from a queue consumer, 404 is noise. The domain names the failure; each driving adapter translates it into its own protocol.",
      },
      {
        q: "redeemReward is called from an HTTP handler today. Product wants it also triggered by an SQS message. What changes?",
        options: [
          "Write an SQS consumer adapter that parses the message and calls the same use case; wire it in the composition root",
          "Duplicate the use case so each delivery mechanism owns its copy",
          "Add a transport parameter so the use case knows who called it",
          "Extract the logic into an internal HTTP endpoint both can call",
        ],
        answer: 0,
        why: "One use case, many driving adapters. The consumer is a thin translator exactly like the handler: parse the message, call redeemReward, map failures to queue semantics. A strong sentence in a system design discussion: the use case never knows or cares what triggered it.",
      },
      {
        q: "The handler must return 404 when redeemReward throws RewardNotFoundError. What is the right test?",
        options: [
          "An integration test through a real database seeded without the reward",
          "A unit test on the use case, since that is where the error originates",
          "Mock the framework's error middleware and assert it was invoked",
          "Stub the use case to throw RewardNotFoundError, invoke the handler, assert the 404; no repository or database involved",
        ],
        answer: 3,
        why: "The behavior under test is the handler's error mapping, nothing deeper. Because the handler receives the use case via its creator's parameter object, you hand it a stub that throws and check the response. Fast, deterministic, and it survives any storage migration.",
      },
      {
        q: "You are reviewing a handler that ends with:\n\nconst reward = await getReward({ rewardId: req.params.id });\nres.json(reward);\n\nWhat is the risk of returning the domain entity directly?",
        options: [
          "None; reusing the entity avoids maintaining duplicate types",
          "Performance: domain entities are expensive to serialize",
          "The public API contract is now coupled to the domain model; renaming an internal field or adding a sensitive one silently changes or leaks into every response",
          "JSON serialization fails on domain objects",
        ],
        answer: 2,
        why: "The response DTO is the published contract; the entity is a private implementation detail free to evolve. Mapping one to the other in the handler is a few lines that buy you the freedom to refactor the domain without breaking clients — and stop a future internalCostBasis field from shipping to the world.",
      },
      {
        q: "Where do authentication and authorization live in a hexagonal service?",
        options: [
          "Both at the edge; security is a delivery concern",
          "Both in the use case; security is a business concern",
          "Authorization in middleware, authentication in the use case",
          "Authentication at the edge (who is calling, tokens, sessions); authorization that encodes business rules, like may this user redeem this reward, in the use case",
        ],
        answer: 3,
        why: "Verifying a JWT is protocol mechanics, so it stays in the handler or middleware, which then passes a plain userId inward. But whether that user may redeem that reward is a domain decision: put it at the edge and every other driving adapter silently skips it.",
      },
      {
        q: "In a codebase with no separate interface declared for the entry point, what plays the role of the driving port?",
        options: [
          "The Express router that registers the routes",
          "The use case's function signature, e.g. redeemReward(params): Promise<Reward> — the entry contract every driving adapter calls",
          "The RewardRepository interface",
          "The composition root, since it exposes the wired functions",
        ],
        answer: 1,
        why: "A port is a contract, not necessarily an interface keyword. The use case's signature, in domain vocabulary, is exactly that contract, and handler, CLI and consumer all program against it. Say: 'the driving port here is implicit — it is the use case signature itself.'",
      },
      {
        q: "You are reviewing this handler for grantCashback:\n\nconst { orderId, amount } = req.body;\nif (amount < 10) {\n  return res.status(400)\n    .json({ error: 'MIN_AMOUNT_NOT_MET' });\n}\nawait grantCashback({ orderId, amount });\n\nWhat do you flag?",
        options: [
          "The minimum-amount rule is business logic disguised as validation; any other driving adapter calling grantCashback bypasses it, so it moves into the use case",
          "The status should be 422, not 400, for semantic correctness",
          "Nothing; rejecting early saves an unnecessary use case call",
          "The handler should load the Order via OrderRepository to verify the amount",
        ],
        answer: 0,
        why: "That a cashback needs a 10-unit minimum is a rule about the product, not about the request's shape — the payload is perfectly well-formed. This is the classic delivery-edge smell: the guard looks like validation, but a queue consumer or CLI would grant cashback on a 2-unit order. Decisions go up into the use case.",
      },
    ],
  },
  {
    id: "s8",
    title: "Events and Asynchronous Adapters",
    questions: [
      {
        q: "In the interview codebase you find:\n\ninterface EventPublisher {\n  publish(event: RewardRedeemed): Promise<void>;\n}\n\nWhat is this, in hexagonal terms?",
        options: [
          "An infrastructure concern that belongs next to the SNS client code",
          "A driving port, because events drive other services",
          "A driven port defined by the domain, with SNS and in-memory adapters behind it",
          "A decorator wrapping the RewardRepository",
        ],
        answer: 2,
        why: "Announcing that something happened is a capability the use case needs, so the domain defines the port in its own vocabulary. Whether it is backed by snsEventPublisherCreator or a recording in-memory publisher is a wiring decision, not a domain one.",
      },
      {
        q: "In the test helpers you find:\n\nconst recordingPublisherCreator = () => {\n  const published: DomainEvent[] = [];\n  return {\n    publisher: {\n      publish: async (e: DomainEvent) => {\n        published.push(e);\n      },\n    },\n    published,\n  };\n};\n\nWhat is it for?",
        options: [
          "An in-memory EventPublisher adapter that records events so unit tests can assert redeemReward published RewardRedeemed with the right payload",
          "A mock that only becomes valid once generated by a mocking framework",
          "A buffer that batches events before flushing them to SQS",
          "A production optimization to skip publishing during peak load",
        ],
        answer: 0,
        why: "Publishing is an output of the use case, and outputs are what tests assert on. Inject this adapter, run the use case, then assert on the published array: no broker, no framework, no network.",
      },
      {
        q: "You are reviewing redeemReward:\n\nawait rewardRepository.save(reward);\nawait eventPublisher.publish({\n  type: 'RewardRedeemed',\n  rewardId: reward.id,\n});\n\nWhat is the failure mode?",
        options: [
          "The event should be published before the save so consumers are warned early",
          "A crash between the two lines persists the redemption but loses the event forever; two systems, no shared transaction",
          "Nothing; awaiting both calls makes them atomic",
          "publish should not be awaited, to keep the use case fast",
        ],
        answer: 1,
        why: "This is the dual-write problem: the database and the broker cannot commit together, so any crash or publish failure leaves them disagreeing. Naming it and proposing the outbox pattern is exactly the review comment the interviewer is fishing for.",
      },
      {
        q: "What is the outbox pattern?",
        options: [
          "A queue-side dead-letter box for messages that failed processing",
          "Buffering events in memory and flushing them every few seconds",
          "Having the consumer write back an acknowledgment row after processing",
          "Writing the event to an outbox table in the same transaction as the state change, with a separate relay publishing it to the broker afterwards",
        ],
        answer: 3,
        why: "One local transaction guarantees the state change and the pending event are saved together or not at all. The relay then delivers at-least-once, which trades the lost-event problem for the duplicate problem, and duplicates are the one you can actually handle.",
      },
      {
        q: "Your queue delivers at-least-once. What does that mean for the grantCashback consumer?",
        options: [
          "Every message arrives exactly once, though possibly late",
          "Some messages may be silently dropped, so you need a nightly reconciliation job",
          "The same RewardRedeemed event may be delivered more than once, so processing it twice must be safe",
          "Messages always arrive in the order they were published",
        ],
        answer: 2,
        why: "At-least-once means no loss, at the price of duplicates: redeliveries after timeouts, retries after crashes mid-batch. Idempotency is not an optimization for this consumer, it is a correctness requirement.",
      },
      {
        q: "Two ways to make the cashback consumer idempotent: keep a table of processed event IDs, or derive the cashback record's ID from the event ID and write with a conditional put. What is the real difference?",
        options: [
          "Natural idempotency makes the duplicate write itself a no-op; a processed-set is a second write that reintroduces a small dual-write window of its own",
          "They are equivalent; pick whichever is fewer lines",
          "The processed-set is strictly better because it works for any event type",
          "Natural idempotency only works with DynamoDB",
        ],
        answer: 0,
        why: "Check-then-mark against a separate processed table can still double-process between the check and the mark unless both writes share a transaction. A deterministic key makes the operation idempotent by construction, with nothing extra to keep consistent. A strong sentence in a system design discussion: 'I prefer idempotency by construction over idempotency by bookkeeping.'",
      },
      {
        q: "An SQS handler parses a RewardRedeemed message and calls grantCashback. In hexagonal terms, what is this handler?",
        options: [
          "A driven adapter, because SQS is infrastructure",
          "Part of the domain, because it triggers a business rule",
          "A decorator on the grantCashback use case",
          "A driving adapter, the asynchronous sibling of an HTTP handler: parse, validate, call the use case, translate the outcome",
        ],
        answer: 3,
        why: "Driving versus driven is about who initiates the call into the hexagon, not about whether the technology is infrastructure. A queue message drives the system exactly like an HTTP request does, so the handler gets the same review checklist: no business decisions, only translation at the edge.",
      },
      {
        q: "A teammate insists the cashback balance must be updated by the time redeemReward returns. The balance is maintained by an async consumer of RewardRedeemed. What is the honest answer?",
        options: [
          "Have redeemReward poll the balance until the consumer catches up",
          "The system is eventually consistent by design; either accept the lag and reflect it in the UI, or move the balance update into the use case and drop the event for that path",
          "Switch to a FIFO queue, which makes delivery synchronous",
          "Publish the event twice to shrink the lag",
        ],
        answer: 1,
        why: "You cannot have asynchronous decoupling and read-your-writes on the same data at the same time; pretending otherwise with polling just hides the boundary. The sentence to say is: 'eventual consistency is a product decision, so let us make it consciously, not discover it in production.'",
      },
      {
        q: "A producer renames rewardId to id in the RewardRedeemed payload and deploys. What just happened?",
        options: [
          "Nothing; consumers should parse defensively",
          "A minor refactor; the queue does not care about payload shape",
          "A breaking change to a published contract with invisible consumers; event schemas need the same versioning discipline as a public API",
          "It is safe as long as the producer's own test suite passes",
        ],
        answer: 2,
        why: "Unlike a function call, you cannot see who consumes an event, and the compiler will not flag them. Treat the schema as a contract: additive changes only, or explicit versions with a migration window, never in-place renames.",
      },
      {
        q: "A teammate proposes putting an SQS queue between redeemReward and RewardRepository 'for decoupling'. Your verdict?",
        options: [
          "Accidental complexity: the save belongs to the request's consistency boundary, so async buys nothing here and costs idempotency, ordering, and observability",
          "Good idea; queues always improve scalability",
          "Good idea, but only with a FIFO queue",
          "Bad idea only because SQS is slow; Kafka would be fine",
        ],
        answer: 0,
        why: "Async earns its keep across boundaries where the caller genuinely should not wait: notifying other services, absorbing spikes. Inside one use case's own state change it converts a simple await into a distributed system for zero benefit.",
      },
      {
        q: "You are reviewing a consumer:\n\ncase 'RewardCreated':\n  await rewardRepository.save(toReward(event));\n  break;\ncase 'RewardRedeemed': {\n  const reward = await rewardRepository.getById(\n    event.rewardId\n  );\n  reward.status = 'redeemed';\n}\n\nIt assumes RewardCreated always arrives before RewardRedeemed. Sound?",
        options: [
          "Yes; producers publish in order, so consumers receive in order",
          "No; retries, redeliveries, and partitioned topics can invert the order, so the consumer must tolerate it: upsert, or park and retry the early arrival",
          "Yes, as long as both events come from the same service",
          "No, but the fix is a short sleep before getById",
        ],
        answer: 1,
        why: "Cross-message ordering is only guaranteed in narrow cases, such as a single FIFO partition key, and one redelivered message breaks it anyway. Here getById returns null and the handler crashes; a consumer that assumes order is a consumer with a latent production incident.",
      },
      {
        q: "A teammate says: 'our broker advertises exactly-once delivery, so grantCashback does not need to be idempotent.' What do you answer?",
        options: [
          "They are right; exactly-once brokers remove the need for idempotency",
          "They are right, provided the queue is FIFO",
          "Wrong; the fix is to have the outbox relay publish each event only once",
          "Wrong; exactly-once holds only within the broker's narrow scope, and the outbox relay plus consumer retries reintroduce duplicates, so end to end you still have at-least-once",
        ],
        answer: 3,
        why: "Exactly-once processing across system boundaries is not a thing you can buy from a broker; a consumer that crashes after the side effect but before the ack will see the message again. Say: 'I design every consumer as if it will see duplicates, because eventually it will.'",
      },
    ],
  },
  {
    id: "s9",
    title: "Legacy Refactoring and Enforcement",
    questions: [
      {
        q: "You inherit a legacy grantCashback module with zero tests and a mandate to refactor it. What comes first?",
        options: [
          "Extract the RewardRepository port immediately; tests come easier after",
          "Write unit tests for the behavior the spec says it should have",
          "Write characterization tests that pin down what the code actually does today, bugs included",
          "Add strict types and lint rules so the compiler catches regressions",
        ],
        answer: 2,
        why: "Characterization tests capture current behavior as your safety net; testing against the spec would silently 'fix' bugs mid-refactor and you could not tell refactor breakage from intended change. Pin the behavior first, move code second.",
      },
      {
        q: "In legacy-code vocabulary, what is a seam?",
        options: [
          "A place where you can change a program's behavior without editing code in that place",
          "A line in the diff where two modules were merged",
          "Any interface that has more than one implementation",
          "The network boundary between two services",
        ],
        answer: 0,
        why: "A seam lets you substitute a dependency, like swapping the real DynamoDB call for a fake, without touching the code under test. In TypeScript the cleanest seam is a function parameter, which is why the Creator pattern is a seam factory.",
      },
      {
        q: "A legacy function reads:\n\nconst grantCashback = async (orderId: string) => {\n  const order = await dynamo\n    .get({ Key: { orderId } })\n    .promise();\n  const amount = order.Item.total * 0.05;\n  await ses.sendEmail(receiptFor(orderId, amount)).promise();\n};\n\nA teammate proposes extracting OrderRepository, CashbackService and a Notifier port in one PR. What do you say?",
        options: [
          "Agree; one big extraction keeps the final design coherent",
          "Extract nothing until the email logic is deleted",
          "Extract all the ports but keep instantiating adapters inline for now",
          "Extract one port, the one blocking tests, ship it, then repeat",
        ],
        answer: 3,
        why: "One seam per PR keeps the diff reviewable and the code shippable at every step. Start with the dependency that hurts most in tests, usually the database, leave the rest untouched, and iterate.",
      },
      {
        q: "What defines a strangler fig migration?",
        options: [
          "Freezing the legacy system while a replacement is built alongside it",
          "New code takes over one route or use case at a time while legacy serves the rest, until legacy is deleted",
          "Rewriting the persistence layer first because it carries the most risk",
          "Running every feature in both systems and comparing outputs forever",
        ],
        answer: 1,
        why: "Both systems live in production at once, and traffic shifts to the hexagonal code slice by slice, so value ships continuously and legacy shrinks until deleting it is trivial. Freezing legacy is exactly what strangler avoids, because the business will not wait.",
      },
      {
        q: "Why do big-bang rewrites of legacy systems reliably fail?",
        options: [
          "The legacy code encodes years of undocumented rules, keeps changing during the rewrite, and nothing shippable exists until the very end",
          "New frameworks are usually slower than mature legacy code",
          "Rewrites need the whole team, so nobody maintains the legacy system",
          "Management never funds them for long enough",
        ],
        answer: 0,
        why: "The target moves while you chase feature parity, and the rules were never written down anywhere but the code you are discarding. The sentence to say is: 'I never propose a rewrite when I can propose a seam.'",
      },
      {
        q: "A teammate opens a long-lived refactor/hexagon branch to migrate the rewards service 'properly'. What is the strongest objection?",
        options: [
          "Long-lived branches make code review sessions too long",
          "The branch will conflict with main and waste time on rebases",
          "The migration must land as small PRs, each leaving main green and deployable; the branch guarantees one risky merge and an unshippable in-between state",
          "Refactors should only happen during a feature freeze",
        ],
        answer: 2,
        why: "Conflicts and slow review are symptoms; the disease is losing shippability. Every intermediate commit should compile, pass tests, and be deployable, which is the strangler principle applied at PR scale.",
      },
      {
        q: "You open src/domain/redeemReward.ts and see:\n\nimport { DynamoDB } from 'aws-sdk';\n\nWhat is broken?",
        options: [
          "Nothing, as long as the client is injected rather than constructed here",
          "The dependency rule: domain code imports nothing from the outside world, no SDKs, no adapters, no frameworks",
          "Only naming: the import should be aliased to a domain type",
          "The file should use @aws-sdk/client-dynamodb, since the v2 SDK is deprecated",
        ],
        answer: 1,
        why: "This value import loads the SDK into every unit test of the domain, and even rewriting it as a type-only import would still couple the domain to a vendor's shapes. DynamoDB may appear only inside dynamoDbRewardRepositoryCreator, and the rule is mechanical enough for a linter to enforce.",
      },
      {
        q: "How do you make 'the domain imports nothing external' survive team turnover?",
        options: [
          "Document the rule in the README and the onboarding deck",
          "Rely on code review to catch violations",
          "Add a pre-commit hook that greps domain files for 'aws-sdk'",
          "Encode it as a dependency-cruiser or ESLint no-restricted-imports rule that fails CI on any forbidden edge",
        ],
        answer: 3,
        why: "Documentation and review discipline decay; a machine-checked rule does not. dependency-cruiser expresses 'src/domain may not reach src/adapters or node_modules' as config, and a red build is the only enforcement that scales. A grep hook catches one SDK, not the rule.",
      },
      {
        q: "What should the top level of the repo tell a reader in five seconds?",
        options: [
          "The architecture: domain, ports, and adapters visible as folders, so the dependency rule maps onto the file tree",
          "The frameworks in use, so newcomers recognize the stack",
          "The team ownership boundaries from the org chart",
          "Nothing; folder layout is cosmetic and only imports matter",
        ],
        answer: 0,
        why: "When structure mirrors architecture, import rules become folder-to-folder constraints and every violation is visible in a file path. A tree that says controllers, models, helpers, utils tells you the stack, not the system.",
      },
      {
        q: "Which name fits the house convention for this factory?\n\nconst ??? = ({\n  pool,\n}: {\n  pool: Pool;\n}): RewardRepository => ({\n  ...\n});",
        options: [
          "RewardRepositoryImpl",
          "createRewardRepository",
          "postgresRewardRepositoryCreator",
          "makePgRepo",
        ],
        answer: 2,
        why: "The convention is technology plus port plus the Creator suffix: a function receiving its own dependencies as a parameter object and returning a port implementation. The name states which adapter it is and which port it satisfies, and grepping for Creator lists every adapter in the codebase.",
      },
      {
        q: "You get five minutes alone with an unfamiliar interview codebase. What tells you the most, fastest?",
        options: [
          "Run the test suite and check the coverage numbers",
          "Grep for process.env and follow the domain's imports: config confined to one wiring file and a dependency-free domain means the architecture is real",
          "Read the README and the architecture diagrams first",
          "Count files per folder to gauge module balance",
        ],
        answer: 1,
        why: "Diagrams describe intent; imports describe reality. If process.env leaks into twelve files or the domain pulls in an SDK, the hexagon is decoration. A strong sentence in a system design discussion: 'I judge architecture by import direction, not by folder names.'",
      },
      {
        q: "A 40-line one-off script exports yesterday's redeemed Rewards to CSV and will be deleted next sprint. Ports and adapters?",
        options: [
          "Yes; consistency across the codebase beats case-by-case judgment",
          "Yes, but only a RewardRepository port, skipping the composition root",
          "No, but wrap it in a use case class for future reuse",
          "No; the architecture pays for itself through change and tests, and a throwaway script has neither, so inline the SDK calls and move on",
        ],
        answer: 3,
        why: "Hexagonal structure is an investment whose return comes from swapping adapters and testing the domain in isolation; a disposable script never collects that return. Knowing when not to apply the pattern is itself a senior signal in the interview.",
      },
    ],
  },
  {
    id: "s10",
    title: "Vocabulary, Smells and Phrasing",
    questions: [
      {
        q: "Dependency inversion and dependency injection are often used interchangeably. What is the actual distinction?",
        options: [
          "They are synonyms; 'inversion' is simply the older term",
          "Injection is the principle, inversion is the SOLID pattern that implements it",
          "Inversion is a design principle about the direction of source-code dependencies; injection is a construction technique for supplying collaborators from outside",
          "Inversion requires a framework container; injection can be done by hand",
        ],
        answer: 2,
        why: "Inversion says the use case depends on a port it owns instead of on DynamoDB. Injection is merely how the collaborator arrives: passed in as an argument. You can inject without inverting — handing a use case a concrete DynamoDB client is still injection, and still coupling.",
      },
      {
        q: "In test-double vocabulary, what makes the object returned by inMemoryRewardRepositoryCreator a fake rather than a stub?",
        options: [
          "It has a real working implementation with its own state, not canned answers",
          "It records every call so you can assert on the calls afterwards",
          "It fails the test when an unexpected method is invoked",
          "It is only permitted in integration tests, never in unit tests",
        ],
        answer: 0,
        why: "A fake genuinely works — a Map behind the RewardRepository port. A stub returns pre-programmed values; a spy records calls for later assertions. Using these three words precisely is a cheap credibility win in an interview.",
      },
      {
        q: "A teammate says 'we should reduce coupling and reduce cohesion in this module.' What is wrong with that sentence?",
        options: [
          "Nothing; both properties should be minimized",
          "Coupling should actually be maximized inside a module",
          "Coupling and cohesion are the same property viewed from two sides",
          "Cohesion is desirable: you want low coupling between modules and high cohesion within them",
        ],
        answer: 3,
        why: "Coupling measures how much modules depend on each other's internals; cohesion measures how well a module's own contents belong together. The hexagon aims for exactly this pairing: low coupling across the port boundary, high cohesion inside the domain.",
      },
      {
        q: "In a system design discussion, why is 'boundary' a more precise word than 'layer' for hexagonal architecture?",
        options: [
          "Layers are deprecated terminology since Clean Architecture",
          "A boundary separates inside from outside with all dependencies pointing inward; layers imply a stack where each level may depend on the one below, including infrastructure",
          "Boundaries only exist at the network edge, layers exist in code",
          "They are interchangeable; hexagonal is layered architecture drawn as a hexagon",
        ],
        answer: 1,
        why: "In classic layering the domain sits on top of a data layer and depends on it. The hexagon has one rule instead of a stack: everything points inward across the boundary. 'The domain owns the boundary' is a strong sentence in a system design discussion.",
      },
      {
        q: "A port in the interview codebase reads:\n\ninterface RewardRepository {\n  query(params: DynamoDB.QueryInput):\n    Promise<DynamoDB.QueryOutput>;\n}\n\nWhat is the name of this smell?",
        options: [
          "Leaky abstraction: vendor types bleed through the port, so every caller is coupled to DynamoDB anyway",
          "God port: the interface has accumulated too many responsibilities",
          "Anemic domain model: the entities hold data but no behavior",
          "Primitive obsession: domain concepts encoded as raw strings",
        ],
        answer: 0,
        why: "The interface exists but abstracts nothing — swap the database and every use case breaks, because the port speaks DynamoDB, not the domain. A port must trade in domain vocabulary: Reward in, Reward out. The sentence to say is: 'this port leaks its adapter.'",
      },
      {
        q: "You are reviewing:\n\ninterface RewardService {\n  getById(id: string): Promise<Reward | null>;\n  save(reward: Reward): Promise<void>;\n  redeem(rewardId: string): Promise<void>;\n  grantCashback(orderId: string): Promise<void>;\n  sendEmail(to: string, body: string): Promise<void>;\n  exportCsv(): Promise<string>;\n  auditLog(entry: string): Promise<void>;\n}\n\nWhat is your diagnosis and remedy?",
        options: [
          "It is fine; one interface per module keeps the wiring simple",
          "Too many adapters will be needed; merge the implementations instead",
          "A god port violating interface segregation: split it into role-shaped ports (RewardRepository, RedemptionService, CashbackService) so each consumer depends only on what it uses",
          "The smell is purely naming; rename it to RewardManager",
        ],
        answer: 2,
        why: "A god port couples every consumer to every capability and makes fakes miserable to write — seven methods to implement to test one. Interface segregation says clients should depend on narrow interfaces shaped by their own needs.",
      },
      {
        q: "Inside redeemReward you find:\n\nif (process.env.NODE_ENV === 'test') {\n  return { granted: true };\n}\n\nWhat do you say in the review?",
        options: [
          "Acceptable pragmatism for a path that is genuinely hard to test",
          "The domain knows about its environment; process.env belongs only in the composition root, and this shortcut means tests exercise a fake branch instead of the real behavior",
          "Move the environment check down into the adapter so the domain stays clean",
          "Inject NODE_ENV through a Config port so the check becomes testable",
        ],
        answer: 1,
        why: "Two smells in three lines: config read outside the wiring, and test-awareness baked into production code. Injecting NODE_ENV through a port keeps the second smell alive. Delete the branch and make the path testable with a fake behind the port.",
      },
      {
        q: "In a live code review, what is the strongest structure for delivering a finding?",
        options: [
          "Walk every file top to bottom listing all issues so nothing is missed",
          "Lead with the fix immediately so you sound decisive",
          "Only ask questions; never state an opinion out loud",
          "Diagnosis, principle, remedy: name what you see, name the rule it breaks, propose the concrete change",
        ],
        answer: 3,
        why: "'This adapter filters rewards — that is a decision, and adapters translate, they never decide — I would lift the filter into the use case.' Three beats, one sentence each. It shows judgment, not just pattern-spotting.",
      },
      {
        q: "An interviewer asks how your design handles vendor lock-in. The sentence to say is:",
        options: [
          "'The vendor is a detail behind a port; leaving it costs one new adapter plus a line in the composition root'",
          "'We avoid managed services entirely, so we are never locked in'",
          "'We wrap every SDK in a helper class, so lock-in is impossible'",
          "'Lock-in is a procurement concern, not an architecture concern'",
        ],
        answer: 0,
        why: "It names the mechanism (a port), the exit cost (one adapter, one wiring change), and the proof is already in the codebase: the in-memory adapter demonstrates the swap. Wrapping an SDK without owning the interface shape is exactly how leaky abstractions are born.",
      },
      {
        q: "What is a seam?",
        options: [
          "Any interface between two deployed microservices",
          "The line in the composition root where two adapters are wired together",
          "A place where you can change a program's behavior without editing the code in that place",
          "A failing test that marks where legacy code breaks",
        ],
        answer: 2,
        why: "That is Feathers' definition, and it is the one to quote. Every port is a deliberate seam: substitute a fake at the seam and redeemReward behaves differently under test without a single edit to its source.",
      },
      {
        q: "The iFeelGoods API models 'vouchers' with statuses that do not map onto your Reward lifecycle. What is the name of the code that shields your domain from their model, and where does it live?",
        options: [
          "A shared kernel, in a common package both systems import",
          "An anti-corruption layer, inside the adapter at the boundary — it translates voucher-speak into your Reward vocabulary so foreign concepts never enter the domain",
          "A facade, inside the use case next to the business rules",
          "A saga, registered in the composition root",
        ],
        answer: 1,
        why: "'Anti-corruption layer' is the DDD name for a translating boundary against a foreign model. In this codebase it is simply a disciplined adapter: iFeelGoodsRedemptionServiceCreator maps their vouchers to domain types and keeps their lifecycle out of yours.",
      },
      {
        q: "Which is the strongest trade-off sentence about hexagonal architecture for an interview?",
        options: [
          "'It has no real downsides once the team knows the pattern'",
          "'It is slower at runtime, but the code is cleaner'",
          "'It only pays off once you move to microservices'",
          "'It buys testability and the option to swap infrastructure, at the price of indirection and extra files — worth it where the domain is the asset, overkill for a thin CRUD app'",
        ],
        answer: 3,
        why: "Naming the cost is what makes the claim credible; zealotry reads as junior. A bounded sentence — what it buys, what it costs, when you would not use it — is a strong sentence in a system design discussion.",
      },
    ],
  },
];
